// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team5618.robot.subsystems;

import org.usfirst.frc.team5618.robot.RobotMap;
import org.usfirst.frc.team5618.robot.commands.BrasCommand;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Bras extends Subsystem {
	private final CANTalon motorBras = RobotMap.brasmotorBras;
	private final DigitalInput limitBrasHaut = RobotMap.brasLimitBrasHaut;
	private final DigitalInput limitBrasBas = RobotMap.brasLimitBrasBas;

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void controlBras(double spd) {
		motorBras.set(-spd);
	}

	public boolean switchHaut() {
		return limitBrasHaut.get();
	}

	public boolean switchBas() {
		return limitBrasBas.get();
	}
	
	public void baisserBras() {
		motorBras.set(0.6);
	}

	public void initDefaultCommand() {

		 setDefaultCommand(new BrasCommand());		
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}
}
