// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team5618.robot.subsystems;

import org.usfirst.frc.team5618.robot.RobotMap;
import org.usfirst.frc.team5618.robot.commands.StopPelle;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Pelle extends Subsystem {

	private final CANTalon motorPelle = RobotMap.pellemotorPelle;
	private final DigitalInput limitPelleBallon = RobotMap.pelleLimitPelleBallon;

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void inBallon() {
		motorPelle.set(1);
	}

	public void outBallon() {
		motorPelle.set(-1);
	}
	
	public void ballonStop() {
		motorPelle.set(0);
	}

	public boolean limitFond() {
		return limitPelleBallon.get();
	}

	public void initDefaultCommand() {

		// Set the default command for a subsystem here.
		setDefaultCommand(new StopPelle());
	}
}
